// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqcirgtwzdychryjbygr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxY2lyZ3R3emR5Y2hyeWpieWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDY0ODUsImV4cCI6MjA3MzAyMjQ4NX0.qn8Ww--U2tbe_8H_QsjXgWL2J0FU8Fk6OlY5w2W2HBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});